services:
  - type: web
    name: insurance-streamlit-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend.py --server.port=10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
